# Generated by Django 5.2 on 2025-04-03 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('employee_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='ID do Funcionário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.CharField(choices=[('19"', 'Monitor 19"'), ('21"', 'Monitor 21"'), ('24"', 'Monitor 24"'), ('27"', 'Monitor 27"')], max_length=3, verbose_name='Monitor')),
                ('keyboard', models.BooleanField(default=True, verbose_name='Teclado')),
                ('mouse', models.BooleanField(default=True, verbose_name='Mouse')),
                ('mousepad', models.BooleanField(default=True, verbose_name='Mousepad')),
                ('headset', models.BooleanField(default=True, verbose_name='Fone de Ouvido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pam.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Estação de Trabalho',
                'verbose_name_plural': 'Estações de Trabalho',
            },
        ),
    ]
