# Generated by Django 5.2 on 2025-04-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
