# Generated by Django 5.2 on 2025-04-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0003_remove_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='category',
            field=models.CharField(choices=[('ESTAGIO', 'Estágio'), ('INSS', 'INSS'), ('SIAPE_DION', 'SIAPE Dion'), ('SIAPE_LEO', 'SIAPE Leo')], default='ESTAGIO', max_length=20, verbose_name='Categoria'),
        ),
    ]
