# Generated by Django 5.2 on 2025-04-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0004_workstation_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['category', 'sequence'], 'verbose_name': 'Estação de Trabalho', 'verbose_name_plural': 'Estações de Trabalho'},
        ),
        migrations.AddField(
            model_name='workstation',
            name='sequence',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Sequência'),
        ),
        migrations.AlterUniqueTogether(
            name='workstation',
            unique_together={('category', 'sequence')},
        ),
    ]
