# Generated by Django 5.2 on 2025-04-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0005_alter_workstation_options_workstation_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='monitor',
            field=models.BooleanField(default=True, verbose_name='Monitor'),
        ),
    ]
