# Generated by Django 5.2 on 2025-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0006_alter_workstation_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='status',
            field=models.CharField(choices=[('OCCUPIED', 'Ocupada'), ('UNOCCUPIED', 'Vaga'), ('MAINTENANCE', 'Manutenção')], default='UNOCCUPIED', max_length=20, verbose_name='Status'),
        ),
    ]
