# Generated by Django 5.1.2 on 2025-04-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0007_workstation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pam.employee', verbose_name='Funcionário'),
        ),
    ]
