# Generated by Django 5.2 on 2025-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0008_remove_employee_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sector',
            field=models.CharField(choices=[('INSS', 'INSS'), ('SIAPE_LEO', 'SIAPE Leo'), ('SIAPE_DION', 'SIAPE Dion'), ('ESTAGIO', 'Estágio')], default='INSS', max_length=20, verbose_name='Setor'),
        ),
    ]
