# Generated by Django 5.2 on 2025-04-09 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0009_employee_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_number', models.PositiveIntegerField(verbose_name='Número da Ilha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ilha',
                'verbose_name_plural': 'Ilhas',
                'ordering': ['room', 'island_number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['island__room__name', 'island__island_number', 'sequence'], 'verbose_name': 'Estação de Trabalho', 'verbose_name_plural': 'Estações de Trabalho'},
        ),
        migrations.AlterField(
            model_name='workstation',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sequência'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='island',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='pam.island', verbose_name='Ilha'),
        ),
        migrations.AddField(
            model_name='island',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islands', to='pam.room', verbose_name='Sala'),
        ),
        migrations.AlterUniqueTogether(
            name='island',
            unique_together={('room', 'island_number')},
        ),
    ]
