# Generated by Django 5.2 on 2025-04-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0010_island_room_alter_workstation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria da Ilha'),
        ),
    ]
