# Generated by Django 5.2 on 2025-04-09 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0011_island_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 123.456.789-00 ou 12345678900', max_length=14, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato: (XX) XXXXX-XXXX', max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
