# Generated by Django 5.2 on 2025-04-09 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0012_employee_cpf_employee_email_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(default='PLACEHOLDER_CPF', help_text='Formato: 123.456.789-00 ou 12345678900', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='PLACEHOLDER_PHONE', help_text='Formato: (XX) XXXXX-XXXX', max_length=15, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
