# Generated by Django 5.2 on 2025-05-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
