# Generated by Django 5.2 on 2025-05-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0015_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='category',
            field=models.CharField(choices=[('ESTAGIO', 'Estágio'), ('INSS', 'INSS'), ('SIAPE_DION', 'SIAPE Dion'), ('SIAPE_LEO', 'SIAPE Leo')], default='INSS', max_length=50, verbose_name='Categoria da Ilha'),
        ),
    ]
