# Generated by Django 5.2 on 2025-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0016_alter_island_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome da Ilha'),
        ),
    ]
