# Generated by Django 5.2 on 2025-05-07 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0017_island_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('WORKSTATION', 'Estação de Trabalho'), ('EMPLOYEE', 'Funcionário'), ('ISLAND', 'Ilha'), ('ROOM', 'Sala')], max_length=20, verbose_name='Tipo de Entidade')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID da Entidade')),
                ('entity_name', models.CharField(max_length=255, verbose_name='Nome da Entidade')),
                ('action_type', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('ASSIGNMENT', 'Atribuição de Funcionário'), ('UNASSIGNMENT', 'Remoção de Funcionário')], max_length=20, verbose_name='Tipo de Ação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Alteração',
                'verbose_name_plural': 'Logs de Alterações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='pam.employee', verbose_name='Funcionário')),
                ('island', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pam.island', verbose_name='Ilha')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pam.room', verbose_name='Sala')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_history', to='pam.workstation', verbose_name='Estação de Trabalho')),
            ],
            options={
                'verbose_name': 'Histórico de Posição',
                'verbose_name_plural': 'Históricos de Posições',
                'ordering': ['-start_date'],
            },
        ),
    ]
