# Generated by Django 5.2 on 2025-05-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0018_changelog_employeepositionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
